"""add is_active to user

Revision ID: 386096d94723
Revises: a3b1702056a6
Create Date: 2025-12-27 20:53:30.579997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386096d94723'
down_revision = 'a3b1702056a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
