"""add sub admin system

Revision ID: 962e5d26e30d
Revises: efb414c17986
Create Date: 2025-12-24 19:35:53.373025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962e5d26e30d'
down_revision = 'efb414c17986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'admin_roles', ['admin_role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_login')
        batch_op.drop_column('admin_role_id')
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###
