"""add admin role and permission

Revision ID: a3b1702056a6
Revises: 962e5d26e30d
Create Date: 2025-12-24 20:31:54.183521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b1702056a6'
down_revision = '962e5d26e30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('admin_role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admin_role_permissions_permission_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'permissions', ['permission_id'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('admin_role_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_role_permissions_permission_id_fkey'), 'admin_permissions', ['permission_id'], ['id'])

    op.drop_table('permissions')
    # ### end Alembic commands ###
