"""added small job extra feilds

Revision ID: a9c404e9baaf
Revises: 234a9d3dd4b6
Create Date: 2025-11-14 20:12:43.199740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c404e9baaf'
down_revision = '234a9d3dd4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gov_id_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gov_id_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('id_proof_file', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('company_registration_number', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('company_linkedin', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('workplace_safety_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cctv_present', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('number_of_employees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('working_hours', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('off_days', sa.String(length=100), nullable=True))

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('job_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('age_requirement_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('age_requirement_max', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('age_requirement_max')
        batch_op.drop_column('age_requirement_min')
        batch_op.drop_column('job_deadline')
        batch_op.drop_column('job_start_date')

    with op.batch_alter_table('employer_profile', schema=None) as batch_op:
        batch_op.drop_column('off_days')
        batch_op.drop_column('working_hours')
        batch_op.drop_column('number_of_employees')
        batch_op.drop_column('cctv_present')
        batch_op.drop_column('workplace_safety_score')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('company_linkedin')
        batch_op.drop_column('company_registration_number')
        batch_op.drop_column('id_proof_file')
        batch_op.drop_column('gov_id_number')
        batch_op.drop_column('gov_id_type')

    # ### end Alembic commands ###
