"""added role and id fields to user

Revision ID: b7558050409c
Revises: f9decee2065a
Create Date: 2025-11-15 15:22:47.940336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7558050409c'
down_revision = 'f9decee2065a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gov_id_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gov_id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gov_id_file', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gov_id_file')
        batch_op.drop_column('gov_id_number')
        batch_op.drop_column('gov_id_type')
        batch_op.drop_column('address')
        batch_op.drop_column('gender')
        batch_op.drop_column('dob')
        batch_op.drop_column('phone')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
